# NUMPY

In [1]:
import numpy as np

In [2]:
lista = [1,2,3,4,5,6,7,8,9,10]

In [3]:
array = np.array(lista)

In [4]:
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [5]:
lista2 = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
lista2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
array2 = np.array(lista2)

In [8]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Numpy arrays - arange, zeros, ones, linspace, eye

In [9]:
import numpy as np

In [10]:
array = np.arange(5) #Genera un array con una secuencia del 0 al 4 (5-1)

In [11]:
array

array([0, 1, 2, 3, 4])

In [12]:
np.arange(2,8) #Genera un array del 2 hasta el 7 (8-1)

array([2, 3, 4, 5, 6, 7])

In [13]:
np.arange(2,20,4) #Genera un array del 2 hasta el 19(20-1) de 4 en 4

array([ 2,  6, 10, 14, 18])

In [14]:
np.zeros(5) #Genera un array de largo 5, con puros 0 

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros([5,10]) #Array de dos dimensiones, filas x columnas

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
array = np.ones(5) #Genera un array de largo 5, con puros 1

In [17]:
np.ones([7,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.linspace(6,8,50) #Genera un array que parte del 6, termina en 8 y tiene 50 espacios


array([6.        , 6.04081633, 6.08163265, 6.12244898, 6.16326531,
       6.20408163, 6.24489796, 6.28571429, 6.32653061, 6.36734694,
       6.40816327, 6.44897959, 6.48979592, 6.53061224, 6.57142857,
       6.6122449 , 6.65306122, 6.69387755, 6.73469388, 6.7755102 ,
       6.81632653, 6.85714286, 6.89795918, 6.93877551, 6.97959184,
       7.02040816, 7.06122449, 7.10204082, 7.14285714, 7.18367347,
       7.2244898 , 7.26530612, 7.30612245, 7.34693878, 7.3877551 ,
       7.42857143, 7.46938776, 7.51020408, 7.55102041, 7.59183673,
       7.63265306, 7.67346939, 7.71428571, 7.75510204, 7.79591837,
       7.83673469, 7.87755102, 7.91836735, 7.95918367, 8.        ])

In [19]:
np.linspace(3,20,18)

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.,
       16., 17., 18., 19., 20.])

In [20]:
np.eye(6) #Genera una matriz cuadrada 

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Números aleatorios - rand y randn


In [21]:
import numpy as np

In [22]:
np.random.rand(5) #Genera un array de 5 espacios de n° aleatorios 

array([0.07886947, 0.8362588 , 0.85740949, 0.98019283, 0.92724202])

In [23]:
np.random.rand(2,3) #Genera una matriz(2x3) de n° aleatorios 

array([[0.1734804 , 0.30332088, 0.12800277],
       [0.94707192, 0.74886473, 0.76428844]])

In [24]:
np.random.randn(4) 

array([ 1.56922711,  1.35213392, -1.14522301,  2.11062473])

In [25]:
np.random.randn(6,9)

array([[-0.74184855, -0.40255422, -2.08792138,  0.23374031, -0.76862083,
         0.8268144 ,  0.3413053 , -0.23787859, -0.44487296],
       [ 2.17896189,  0.94464398,  0.29071185,  0.46498579, -0.78678341,
         0.49759465, -0.62734261, -0.33543859, -0.43741525],
       [-1.34004055, -0.88765912, -1.62795703,  0.07242913,  1.8195539 ,
        -0.8284096 ,  0.03497255, -0.38191219,  1.50365189],
       [-0.10321373, -1.12948207, -2.76547625,  0.76691771,  0.73606901,
        -0.48274772,  0.95081599,  1.22667184,  0.24106659],
       [-0.4088938 ,  0.37724582, -2.01562363,  0.55698989,  1.01348596,
        -0.75299368, -0.21514301,  1.18329487, -0.5040947 ],
       [-0.74302857, -0.17342422,  0.25422234, -1.04169345, -1.13895536,
        -0.09091421, -1.07301321,  0.91370689,  2.33613931]])

# numpy arrays - números aleatorios enteros y randint

In [26]:
import numpy as np

In [27]:
np.random.randint(1,20) #Genera 1 número random entre el 1 y el 19 (20-1)

16

In [28]:
np.random.randint(1,20,5) #Genera un array de 5 espacios con números random entre el 1 y el 19 (20-1)

array([ 9, 19,  4,  5, 12])

# Numpy arrays - reshape


In [29]:
import numpy as np

In [30]:
array = np.random.randint(1,100,21) #Genera una array de 21 espacios con numeros random del 1 al 99 (100-1)

In [31]:
array

array([ 5, 45, 47, 77, 37,  4, 30,  6, 21, 89, 44, 15, 38,  2, 50, 36, 35,
        3,  3, 77, 12])

In [32]:
matriz = array.reshape(3,7) #A partir de un array, genera una matriz (3x7)

In [33]:
matriz

array([[ 5, 45, 47, 77, 37,  4, 30],
       [ 6, 21, 89, 44, 15, 38,  2],
       [50, 36, 35,  3,  3, 77, 12]])


# Numpy arrays - max y min

In [34]:
import numpy as np

In [35]:
array = np.random.randint(1,100,50) #Genera una array de 50 espacios con numeros random del 1 al 99 (100-1)

In [36]:
array

array([80, 55, 79, 91, 24, 98, 15, 73, 76, 36, 14, 51, 82, 25, 48, 23, 43,
       74, 87, 95,  5, 68, 11, 72, 14, 45, 95, 64, 33, 86, 38,  3, 11, 33,
       19, 88, 86, 24,  2,  4, 51, 77, 54,  1, 35, 25, 91, 39, 61, 18])

In [37]:
valor_maximo = array.max()

In [38]:
valor_maximo

98

In [39]:
posicion_valor_maximo = array.argmax() #Dice en que posicion del array esta el maximo 

In [40]:
posicion_valor_maximo

5

In [41]:
valor_minimo = array.min()

In [42]:
valor_minimo

1

In [43]:
posicion_valor_minimo = array.argmin() #Dice en que posicion del array esta el mínimo 

In [44]:
posicion_valor_minimo

43

# Numpy - Indexación en Arrays

In [45]:
import numpy as np

In [46]:
array = np.arange(0,10)

In [47]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
array[0] #valor en la posición 0

0

In [49]:
array[4] #valor en la posición 4

4

In [50]:
array[-1] #valor en la ultima posición 

9

In [51]:
array[2:4] #valores de la posición 2, hasta la 3 (4-1)

array([2, 3])

In [52]:
array[2:8] #valores de la posición 2, hasta la 7 (8-1)

array([2, 3, 4, 5, 6, 7])

In [53]:
array[:] 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
array[2:] #valores de la posición 5, hasta la ultima

array([2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
array[:5] #valores de la primera posición, hasta la posición 4 (5-1)

array([0, 1, 2, 3, 4])

In [56]:
array2 = array.copy()

In [57]:
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Numpy - indexación en arrays de 2 o más dimensiones

In [58]:
import numpy as np

In [59]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [60]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
array[0]

array([1, 2, 3])

In [62]:
array[2]

array([7, 8, 9])

In [63]:
array[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
array2 = array[:2]

In [65]:
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
array[0][0]

1

In [68]:
array[0,0]

1

In [69]:
array[1,1]

5

In [70]:
array[:,0]

array([1, 4, 7])

In [71]:
array[:,2]

array([3, 6, 9])

In [72]:
array[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Numpy - Sleccionar elementos de un array según una condición

In [73]:
import numpy as np

In [74]:
array = np.arange(0,10)

In [75]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
condicion = array > 5

In [77]:
condicion

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [78]:
array[condicion]

array([6, 7, 8, 9])

In [79]:
array6 = array[condicion]

In [80]:
array6

array([6, 7, 8, 9])

In [81]:
array[array > 5]

array([6, 7, 8, 9])

In [82]:
array[array % 2]

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [83]:
array[array % 2 == 0]

array([0, 2, 4, 6, 8])

In [84]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Numpy - Operaciones sobre los arrays

In [85]:
import numpy as np

In [86]:
array = np.arange(0,10)

In [87]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
array + array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [89]:
array - array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [90]:
array * 100

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [91]:
array + 4

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [92]:
array + 40

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [93]:
array - 1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [94]:
array * -1

array([ 0, -1, -2, -3, -4, -5, -6, -7, -8, -9])

In [95]:
array2 = np.arange(5,15)

In [96]:
array2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [97]:
array 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
array2 - array

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [99]:
array2 + array

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [100]:
array2 * array

array([  0,   6,  14,  24,  36,  50,  66,  84, 104, 126])

In [101]:
np.sqrt(array2)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [102]:
np.max(array)

9

In [103]:
np.min(array)

0