# Ejercicio 1

In [1]:
import numpy as np
import pandas as pd

In [2]:
asignaturas = ['matemáticas','física','historia']
asignaturas

['matemáticas', 'física', 'historia']

In [3]:
notas = [9,9,8]
notas

[9, 9, 8]

In [6]:
serie = pd.Series(notas,asignaturas)
serie

matemáticas    9
física         9
historia       8
dtype: int64

In [8]:
nota_fisica = serie['física']
nota_fisica

9

In [17]:
print("La nota de fisica es: {}".format(nota_fisica) )

La nota de fisica es: 9


In [16]:
print("La nota de fisica es:", nota_fisica )

La nota de fisica es: 9


# Ejercicio 2

In [18]:
import numpy as np
import pandas as pd

In [20]:
ventas_enero = np.random.randint(100,500,3)
ventas_enero

array([243, 108, 367])

In [21]:
ventas_febrero = np.random.randint(100,500,3)
ventas_febrero

array([356, 146, 450])

In [22]:
ventas_marzo = np.random.randint(100,500,3)
ventas_marzo

array([453, 265, 438])

In [23]:
filas = ['ventas_enero','ventas_febrero','ventas_marzo']
filas

['ventas_enero', 'ventas_febrero', 'ventas_marzo']

In [24]:
columnas = ['oficina1','oficina2','oficina3']
columnas

['oficina1', 'oficina2', 'oficina3']

In [26]:
ventas = [ventas_enero,ventas_febrero,ventas_marzo]
ventas

[array([243, 108, 367]), array([356, 146, 450]), array([453, 265, 438])]

In [27]:
dataframe = pd.DataFrame(ventas,filas,columnas)
dataframe

oficina1  oficina2  oficina3
ventas_enero         243       108       367
ventas_febrero       356       146       450
ventas_marzo         453       265       438

In [38]:
dataframe.loc['ventas_enero']

oficina1    243
oficina2    108
oficina3    367
Name: ventas_enero, dtype: int64

In [42]:
ventas_enero_oficina1 = dataframe['oficina1']['ventas_enero']

In [43]:
print("Las ventas de enro para la oficina 1 son de: ", ventas_enero_oficina1)

Las ventas de enro para la oficina 1 son de:  243
