# Ejercicio 1

In [1]:
import numpy as np
import pandas as pd

In [2]:
asignaturas = ['matemáticas','física','historia']
asignaturas

['matemáticas', 'física', 'historia']

In [3]:
notas = [9,9,8]
notas

[9, 9, 8]

In [4]:
serie = pd.Series(notas,asignaturas)
serie

matemáticas    9
física         9
historia       8
dtype: int64

In [5]:
nota_fisica = serie['física']
nota_fisica

9

In [6]:
print("La nota de fisica es: {}".format(nota_fisica) )

La nota de fisica es: 9


In [7]:
print("La nota de fisica es:", nota_fisica )

La nota de fisica es: 9


# Ejercicio 2

In [8]:
import numpy as np
import pandas as pd

In [9]:
ventas_enero = np.random.randint(100,500,3)
ventas_enero

array([466, 116, 159])

In [10]:
ventas_febrero = np.random.randint(100,500,3)
ventas_febrero

array([200, 349, 370])

In [11]:
ventas_marzo = np.random.randint(100,500,3)
ventas_marzo

array([255, 155, 392])

In [12]:
filas = ['ventas_enero','ventas_febrero','ventas_marzo']
filas

['ventas_enero', 'ventas_febrero', 'ventas_marzo']

In [13]:
columnas = ['oficina1','oficina2','oficina3']
columnas

['oficina1', 'oficina2', 'oficina3']

In [14]:
ventas = [ventas_enero,ventas_febrero,ventas_marzo]
ventas

[array([466, 116, 159]), array([200, 349, 370]), array([255, 155, 392])]

In [15]:
dataframe = pd.DataFrame(ventas,filas,columnas)
dataframe

oficina1  oficina2  oficina3
ventas_enero         466       116       159
ventas_febrero       200       349       370
ventas_marzo         255       155       392

In [16]:
dataframe.loc['ventas_enero']

oficina1    466
oficina2    116
oficina3    159
Name: ventas_enero, dtype: int64

In [17]:
ventas_enero_oficina1 = dataframe['oficina1']['ventas_enero']

In [18]:
print("Las ventas de enro para la oficina 1 son de: ", ventas_enero_oficina1)

Las ventas de enro para la oficina 1 son de:  466
