# Ejercicio 1

Crear una lista de números secuenciales con el valor mínimo de 10 y el valor máximo de 39. Convertir esta lista en una lista o matriz de dos dimensiones (3x10).
Mostrar por pantalla el valor del elemento en la esquina superior derecha de la matriz.

In [1]:
import numpy as np

In [2]:
lista = np.arange(10,40)

In [3]:
lista

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [4]:
lista.reshape(3,10)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [5]:
lista.reshape(3,10)[0,9]

19

Crear un array de una dimension con 9 valores entero aleatorios enntre 0 y 100
Convierte ese array en una matriz de 2 dimensiones (3x3)
Muestra por  pantalla el valor del elemento de la matriz, de la esquina inferior derecha

In [6]:
array = np.random.randint(0,100,9)

In [7]:
array

array([32, 39, 59, 48, 19,  2,  1, 48, 96])

In [8]:
array.reshape(3,3)

array([[32, 39, 59],
       [48, 19,  2],
       [ 1, 48, 96]])

In [9]:
array.reshape(3,3)[2,2]

96